export const LOADING_LINES = [
  "Bypassing ethics module...",
  "Injecting coffee into CPU...",
  "Sending packets...",
  "Overclocking decryption...",
  "Spoofing MAC address...",
  "Deploying cyber daemons...",
  "Compiling exploits...",
  "Brute forcing password...",
  "Activating stealth mode...",
  "Loading encryption module...",
  "Reverse engineering firewall...",
  "Injecting malware...",
  "Decrypting classified assets...",
  "Uploading virus...",
  "Checking anonymity...",
  "Scanning ports...",
  "Running exploit...",
  "Disabling security logs...",
  "Faking credentials...",
  "Injecting payload...",
  "Compromising mainframe...",
  "Compiling zero-day exploit...",
  "Fuzzing network...",
  "Hijacking signal...",
  "Scrambling IP...",
  "Deploying worms...",
  "Erasing logs...",
  "Generating fake credentials...",
  "Exploiting buffer overflow...",
  "Decrypting secret messages...",
];
