export const AddressInfoDropdownStyles = {
    details: "dropdown dropdown-end leading-3",
    summary: "btn bg-transparent btn-sm px-2 py-[0.35rem] dropdown-toggle gap-0 !h-auto border border-[#5c4fe5] ",
    divOne: "hidden [@media(min-width:412px)]:block",
    spanOne: "ml-2 mr-2 text-sm",
    chevronDownIcon: "h-6 w-4 ml-2 sm:ml-0 sm:block hidden",
    ul: "dropdown-content menu z-[2] p-2 mt-2 rounded-[5px] gap-1 border border-[#5c4fe5] bg-base-100",
    divTwo: "btn-sm !rounded-xl flex gap-3 py-3",
    checkCircleIcon: "text-xl font-normal h-6 w-4 cursor-pointer ml-2 sm:ml-0",
    divThree: "btn-sm !rounded-xl flex gap-3 py-3",
    duplicateIcon: "text-xl font-normal h-6 w-4 cursor-pointer ml-2 sm:ml-0",
    labelOne: "btn-sm !rounded-xl flex gap-3 py-3",
    QrCode: "h-6 w-4 ml-2 sm:ml-0",
    buttonOne: "menu-item btn-sm !rounded-xl flex gap-3 py-3",
    arrowIcon: "h-6 w-4 ml-2 sm:ml-0",
}